### ISSUE TITLE
Contract Has Not Been Deployed

### ISSUE THREAD

**Issue by marchelhutagalung** [pmarella2/BroncoVotes#1]
Uncaught (in promise) Error: Contract has not been deployed to detected network (network/artifact mismatch

**Comment by pmarella2** [comment]
At which in deployment are you getting this Error?

**Comment by marchelhutagalung** [comment]
Sorry bro, i miss the step

**Comment by marchelhutagalung** [comment]
But, i can't interact with the app, e.g Register to vote, Create Ballot etc.

**Comment by pmarella2** [comment]
Sorry, I have been busy.

Did you figure out why you couldn't interact with anything? Make sure you use the correct domain to register within the voting dApp or it won't let you interact with anything.

**Comment by marchelhutagalung** [comment]
No problem bro.

I'm sorry, which one that you mean 'correct domain'? I use my localhost.

**Comment by pmarella2** [comment]
Well, can you either send me a screenshot of the exact error and what step you are encountering it. This will help me narrow down what is wrong in your build.

**Comment by marchelhutagalung** [comment]
I've followed all the steps, and everything goes well. But when register to vote there is an error.

![image](https://user-images.githubusercontent.com/28001151/52543523-e89a6b80-2ddc-11e9-9948-5c44df5606e6.png)

**Comment by pmarella2** [comment]
That is because when you look at 2_deploy_contracts.js (https://github.com/pmarella2/BroncoVotes/blob/master/migrations/2_deploy_contracts.js), you will see the whitelisted domains for the email addresses used in the application. 
If you pulled recently, your email should have @gmail.com, @yahoo.com, or @hotmail.com
If you have an older version, your email should have @boisestate.edu
