### ISSUE TITLE
Resource Blocked

### ISSUE THREAD

**Issue by SamuelRoberts96** [pmarella2/BroncoVotes#3]
Hi, I followed your instructions for installing and compiling the dapp but when trying to interact with it i get this error and i am not sure how to fix it.

![image](https://user-images.githubusercontent.com/42743618/63700517-febcc600-c81a-11e9-91cf-694bce297126.png)

I tried searching for that url and simply get a 404 error code. I'm not sure if i should replace the url with a different one or whether the issue is something else.

Any advise or help would be greatly appreciated.

Thanks

**Comment by hasnat23** [comment]
Did you find any solution for this error?

**Comment by pmarella2** [comment]
First off, sorry I have been really busy and didn't get a notice for this issue.

But, I think I fixed it. There were some changes that needed to be made to the migrations script (had to convert the strings array to hex due to new data handling by bytes32 data type in Solidity) and hardcoding the compiler version. 

Please update Truffle and pull the current version of the code. It should work. If it doesn't, we can try to troubleshoot it further.

I followed the instructions I included in the README on a fresh copy of Ubuntu and it works perfectly fine with the new changes.
